name: CICD pipeline

on:
  push:
    branches: [ main ]

jobs:
  deploy_code:
    name: deploy_code
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: setup nodejs version
        uses: actions/setup-node@v3
        with:
          node_version: "24.11.0"

      - name: install packages
        run: npm install

      - name: deploy to aws ec2
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          SOURCE: "."
          REMOTE_HOST: "ec2-54-145-1-248.compute-1.amazonaws.com"
          REMOTE_USER: "ubuntu"
          TARGET: "/var/www/aws-cicd-node-test/"

      - name: restart server
        uses: appleboy/ssh-action@master
        with:
          host: "ec2-54-145-1-248.compute-1.amazonaws.com"
          username: "ubuntu"
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: pm2 restart all